import type { MediaItem, Clip, Track } from "./types";
import { DEFAULT_FPS } from "./types";

const sec = (s: number) => Math.round(s * DEFAULT_FPS);

export const MOCK_MEDIA: MediaItem[] = [
  {
    id: "m-mercury-reel",
    name: "Mercury Retrograde — Reel 01.mp4",
    type: "video",
    durationFrames: sec(30),
    fps: DEFAULT_FPS,
    aspect: "9:16",
    thumb: "linear-gradient(135deg, #2a1248 0%, #6a2db5 50%, #f17e2c 100%)",
    clipColor: "#5b3a8c",
  },
  {
    id: "m-birth-chart",
    name: "Birth Chart Reading Tutorial.mp4",
    type: "video",
    durationFrames: sec(12 * 60 + 45),
    fps: DEFAULT_FPS,
    aspect: "16:9",
    thumb: "linear-gradient(135deg, #0a1628 0%, #1d3a6a 60%, #d4a843 100%)",
    clipColor: "#2c5d8a",
  },
  {
    id: "m-saturn-return",
    name: "Saturn Return — Long form.mp4",
    type: "video",
    durationFrames: sec(28 * 60 + 15),
    fps: DEFAULT_FPS,
    aspect: "16:9",
    thumb: "linear-gradient(135deg, #1a0a2e 0%, #4d2660 60%, #c9a063 100%)",
    clipColor: "#623b7a",
  },
  {
    id: "m-moon-pisces",
    name: "Moon in Pisces — IG Story.mp4",
    type: "video",
    durationFrames: sec(15),
    fps: DEFAULT_FPS,
    aspect: "9:16",
    thumb: "linear-gradient(135deg, #06334d 0%, #2a8aa8 50%, #b8e2ec 100%)",
    clipColor: "#3a7d96",
  },
  {
    id: "m-intro",
    name: "Astrology × Psychology Intro.mp4",
    type: "video",
    durationFrames: sec(4 * 60 + 22),
    fps: DEFAULT_FPS,
    aspect: "16:9",
    thumb: "linear-gradient(135deg, #1a3a2e 0%, #3d6a5a 60%, #d4a843 100%)",
    clipColor: "#3e6b7d",
  },
  {
    id: "m-broll-crystals",
    name: "B-roll — Crystals.mp4",
    type: "video",
    durationFrames: sec(45),
    fps: DEFAULT_FPS,
    aspect: "16:9",
    thumb: "linear-gradient(135deg, #2a0a4d 0%, #7a3da8 50%, #f1c2e8 100%)",
    clipColor: "#6b4d96",
  },
  {
    id: "m-cosmic-pop",
    name: "Cosmic Pop — Background Track.mp3",
    type: "audio",
    durationFrames: sec(3 * 60 + 30),
    fps: DEFAULT_FPS,
    aspect: "audio",
    thumb: "linear-gradient(135deg, #1a3a1a 0%, #4d7a3a 100%)",
    clipColor: "#4d7a3a",
  },
  {
    id: "m-vo-welcome",
    name: "Voiceover — Welcome Gabs.wav",
    type: "audio",
    durationFrames: sec(18),
    fps: DEFAULT_FPS,
    aspect: "audio",
    thumb: "linear-gradient(135deg, #2a3a1a 0%, #6ba34d 100%)",
    clipColor: "#6ba34d",
  },
];

export const DEFAULT_TRACKS: Track[] = [
  { id: "v3", label: "V3", type: "video", muted: false, solo: false, locked: false },
  { id: "v2", label: "V2", type: "video", muted: false, solo: false, locked: false },
  { id: "v1", label: "V1", type: "video", muted: false, solo: false, locked: false },
  { id: "a1", label: "A1", type: "audio", muted: false, solo: false, locked: false },
  { id: "a2", label: "A2", type: "audio", muted: false, solo: false, locked: false },
  { id: "a3", label: "A3", type: "audio", muted: false, solo: false, locked: false },
];

export const SEED_CLIPS: Clip[] = [
  {
    id: "c-seed-1",
    mediaId: "m-intro",
    trackId: "v1",
    startFrames: 0,
    inFrames: 0,
    outFrames: sec(8),
  },
  {
    id: "c-seed-2",
    mediaId: "m-broll-crystals",
    trackId: "v1",
    startFrames: sec(8),
    inFrames: 0,
    outFrames: sec(12),
  },
  {
    id: "c-seed-3",
    mediaId: "m-mercury-reel",
    trackId: "v2",
    startFrames: sec(4),
    inFrames: 0,
    outFrames: sec(6),
  },
  {
    id: "c-seed-4",
    mediaId: "m-cosmic-pop",
    trackId: "a1",
    startFrames: 0,
    inFrames: 0,
    outFrames: sec(20),
  },
  {
    id: "c-seed-5",
    mediaId: "m-vo-welcome",
    trackId: "a2",
    startFrames: sec(2),
    inFrames: 0,
    outFrames: sec(18),
  },
];
